package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AvailableProduct generated by hbm2java
 */
@Entity
@Table(name="available_product"
    ,catalog="tml"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class AvailableProduct  implements java.io.Serializable {


     private String productId;
     private int id;
     private String availQuantity;
     private String updateAt;

    public AvailableProduct() {
    }

	
    public AvailableProduct(int id) {
        this.id = id;
    }
    public AvailableProduct(int id, String availQuantity, String updateAt) {
       this.id = id;
       this.availQuantity = availQuantity;
       this.updateAt = updateAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false, length=30)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="avail_quantity", length=30)
    public String getAvailQuantity() {
        return this.availQuantity;
    }
    
    public void setAvailQuantity(String availQuantity) {
        this.availQuantity = availQuantity;
    }

    
    @Column(name="update_at", length=30)
    public String getUpdateAt() {
        return this.updateAt;
    }
    
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt;
    }




}


