package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoryDetails generated by hbm2java
 */
@Entity
@Table(name="category_details"
    ,catalog="tml"
)
public class CategoryDetails  implements java.io.Serializable {


     private Integer id;
     private String categoryName;
     private String categoryDescription;

    public CategoryDetails() {
    }

    public CategoryDetails(String categoryName, String categoryDescription) {
       this.categoryName = categoryName;
       this.categoryDescription = categoryDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="category_name", length=120)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="category_description", length=250)
    public String getCategoryDescription() {
        return this.categoryDescription;
    }
    
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }




}


