package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="tml"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Customer  implements java.io.Serializable {


     private String custId;
     private int id;
     private String custName;
     private String custAddress;
     private String date;
     private String contactNumber01;
     private String contactNumber02;
     private String status;

    public Customer() {
    }

	
    public Customer(int id, String status) {
        this.id = id;
        this.status = status;
    }
    public Customer(int id, String custName, String custAddress, String date, String contactNumber01, String contactNumber02, String status) {
       this.id = id;
       this.custName = custName;
       this.custAddress = custAddress;
       this.date = date;
       this.contactNumber01 = contactNumber01;
       this.contactNumber02 = contactNumber02;
       this.status = status;       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
     
     
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cust_id", unique=true, nullable=false, length=30)
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }
    
    @Column(name="cust_name", length=100)
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }

    
    @Column(name="cust_address", length=200)
    public String getCustAddress() {
        return this.custAddress;
    }
    
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress;
    }

    
    @Column(name="date", length=50)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="contact_number_01", length=30)
    public String getContactNumber01() {
        return this.contactNumber01;
    }
    
    public void setContactNumber01(String contactNumber01) {
        this.contactNumber01 = contactNumber01;
    }

    
    @Column(name="contact_number_02", length=30)
    public String getContactNumber02() {
        return this.contactNumber02;
    }
    
    public void setContactNumber02(String contactNumber02) {
        this.contactNumber02 = contactNumber02;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
}


