package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InStock generated by hbm2java
 */
@Entity
@Table(name="in_stock"
    ,catalog="tml"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class InStock  implements java.io.Serializable {


     private String inStockId;
     private int id;
     private String productId;
     private String supplierId;
     private String date;
     private String quantity;

    public InStock() {
    }

	
    public InStock(int id) {
        this.id = id;
    }
    public InStock(int id, String productId, String supplierId, String date, String quantity) {
       this.id = id;
       this.productId = productId;
       this.supplierId = supplierId;
       this.date = date;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="in_stock_id", unique=true, nullable=false, length=30)
    public String getInStockId() {
        return this.inStockId;
    }
    
    public void setInStockId(String inStockId) {
        this.inStockId = inStockId;
    }

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="product_id", length=30)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="supplier_id", length=30)
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="date", length=30)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="quantity", length=30)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


