package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OutStock generated by hbm2java
 */
@Entity
@Table(name="out_stock"
    ,catalog="tml"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class OutStock  implements java.io.Serializable {


     private String outStockId;
     private int id;
     private String productId;
     private String custId;
     private String date;
     private String quantity;

    public OutStock() {
    }

	
    public OutStock(int id) {
        this.id = id;
    }
    public OutStock(int id, String productId, String custId, String date, String quantity) {
       this.id = id;
       this.productId = productId;
       this.custId = custId;
       this.date = date;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="out_stock_id", unique=true, nullable=false, length=30)
    public String getOutStockId() {
        return this.outStockId;
    }
    
    public void setOutStockId(String outStockId) {
        this.outStockId = outStockId;
    }

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="product_id", length=30)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="cust_id", length=30)
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }

    
    @Column(name="date", length=30)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="quantity", length=30)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


