package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductInfo generated by hbm2java
 */
@Entity
@Table(name="product_info"
    ,catalog="tml"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class ProductInfo  implements java.io.Serializable {


     private String proId;
     private int id;
     private String proName;
     private String proBarcode;
     private String proCategoryId;
     private String proDescription;
     private String proImage;
     private String proDate;

    public ProductInfo() {
    }

	
    public ProductInfo(int id) {
        this.id = id;
    }
    public ProductInfo(int id, String proName, String proBarcode, String proCategoryId, String proDescription, String proImage, String proDate) {
       this.id = id;
       this.proName = proName;
       this.proBarcode = proBarcode;
       this.proCategoryId = proCategoryId;
       this.proDescription = proDescription;
       this.proImage = proImage;
       this.proDate = proDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pro_id", unique=true, nullable=false, length=30)
    public String getProId() {
        return this.proId;
    }
    
    public void setProId(String proId) {
        this.proId = proId;
    }

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="pro_name", length=30)
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }

    
    @Column(name="pro_barcode", length=30)
    public String getProBarcode() {
        return this.proBarcode;
    }
    
    public void setProBarcode(String proBarcode) {
        this.proBarcode = proBarcode;
    }

    
    @Column(name="pro_category_id", length=30)
    public String getProCategoryId() {
        return this.proCategoryId;
    }
    
    public void setProCategoryId(String proCategoryId) {
        this.proCategoryId = proCategoryId;
    }

    
    @Column(name="pro_description", length=30)
    public String getProDescription() {
        return this.proDescription;
    }
    
    public void setProDescription(String proDescription) {
        this.proDescription = proDescription;
    }

    
    @Column(name="pro_image", length=30)
    public String getProImage() {
        return this.proImage;
    }
    
    public void setProImage(String proImage) {
        this.proImage = proImage;
    }

    
    @Column(name="pro_date", length=30)
    public String getProDate() {
        return this.proDate;
    }
    
    public void setProDate(String proDate) {
        this.proDate = proDate;
    }




}


