package com.product.entity;
// Generated Jan 28, 2018 2:52:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockDetails generated by hbm2java
 */
@Entity
@Table(name="stock_details"
    ,catalog="tml"
)
public class StockDetails  implements java.io.Serializable {


     private Integer id;
     private String stockId;
     private String stockName;
     private int stockQuatity;
     private String supplierId;
     private BigDecimal companyPrice;
     private BigDecimal sellingPrice;
     private String category;
     private Date date;
     private Date expireDate;
     private String uom;

    public StockDetails() {
    }

    public StockDetails(String stockId, String stockName, int stockQuatity, String supplierId, BigDecimal companyPrice, BigDecimal sellingPrice, String category, Date date, Date expireDate, String uom) {
       this.stockId = stockId;
       this.stockName = stockName;
       this.stockQuatity = stockQuatity;
       this.supplierId = supplierId;
       this.companyPrice = companyPrice;
       this.sellingPrice = sellingPrice;
       this.category = category;
       this.date = date;
       this.expireDate = expireDate;
       this.uom = uom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="stock_id", nullable=false, length=120)
    public String getStockId() {
        return this.stockId;
    }
    
    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    
    @Column(name="stock_name", nullable=false, length=120)
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    
    @Column(name="stock_quatity", nullable=false)
    public int getStockQuatity() {
        return this.stockQuatity;
    }
    
    public void setStockQuatity(int stockQuatity) {
        this.stockQuatity = stockQuatity;
    }

    
    @Column(name="supplier_id", nullable=false, length=250)
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="company_price", nullable=false, precision=10)
    public BigDecimal getCompanyPrice() {
        return this.companyPrice;
    }
    
    public void setCompanyPrice(BigDecimal companyPrice) {
        this.companyPrice = companyPrice;
    }

    
    @Column(name="selling_price", nullable=false, precision=10)
    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    
    @Column(name="category", nullable=false, length=120)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire_date", nullable=false, length=19)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    
    @Column(name="uom", nullable=false, length=120)
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public void setExpireDate(int TIMESTAMP) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


