package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockEntries generated by hbm2java
 */
@Entity
@Table(name="stock_entries"
    ,catalog="tml"
)
public class StockEntries  implements java.io.Serializable {


     private Integer id;
     private String stockId;
     private String stockName;
     private String stockSupplierName;
     private String category;
     private Integer quantity;
     private BigDecimal companyPrice;
     private BigDecimal sellingPrice;
     private Integer openingStock;
     private Integer closingStock;
     private Date date;
     private String username;
     private String type;
     private String salesid;
     private BigDecimal total;
     private BigDecimal payment;
     private BigDecimal balance;
     private String mode;
     private String description;
     private Date due;
     private Integer subtotal;
     private Integer count1;
     private String billnumber;
     private String status;

    public StockEntries() {
    }

	
    public StockEntries(String status) {
        this.status = status;
    }
    public StockEntries(String stockId, String stockName, String stockSupplierName, String category, Integer quantity, BigDecimal companyPrice, BigDecimal sellingPrice, Integer openingStock, Integer closingStock, Date date, String username, String type, String salesid, BigDecimal total, BigDecimal payment, BigDecimal balance, String mode, String description, Date due, Integer subtotal, Integer count1, String billnumber, String status) {
       this.stockId = stockId;
       this.stockName = stockName;
       this.stockSupplierName = stockSupplierName;
       this.category = category;
       this.quantity = quantity;
       this.companyPrice = companyPrice;
       this.sellingPrice = sellingPrice;
       this.openingStock = openingStock;
       this.closingStock = closingStock;
       this.date = date;
       this.username = username;
       this.type = type;
       this.salesid = salesid;
       this.total = total;
       this.payment = payment;
       this.balance = balance;
       this.mode = mode;
       this.description = description;
       this.due = due;
       this.subtotal = subtotal;
       this.count1 = count1;
       this.billnumber = billnumber;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="stock_id", length=120)
    public String getStockId() {
        return this.stockId;
    }
    
    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    
    @Column(name="stock_name", length=260)
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    
    @Column(name="stock_supplier_name", length=200)
    public String getStockSupplierName() {
        return this.stockSupplierName;
    }
    
    public void setStockSupplierName(String stockSupplierName) {
        this.stockSupplierName = stockSupplierName;
    }

    
    @Column(name="category", length=120)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="company_price", precision=10)
    public BigDecimal getCompanyPrice() {
        return this.companyPrice;
    }
    
    public void setCompanyPrice(BigDecimal companyPrice) {
        this.companyPrice = companyPrice;
    }

    
    @Column(name="selling_price", precision=10)
    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    
    @Column(name="opening_stock")
    public Integer getOpeningStock() {
        return this.openingStock;
    }
    
    public void setOpeningStock(Integer openingStock) {
        this.openingStock = openingStock;
    }

    
    @Column(name="closing_stock")
    public Integer getClosingStock() {
        return this.closingStock;
    }
    
    public void setClosingStock(Integer closingStock) {
        this.closingStock = closingStock;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="username", length=120)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="salesid", length=120)
    public String getSalesid() {
        return this.salesid;
    }
    
    public void setSalesid(String salesid) {
        this.salesid = salesid;
    }

    
    @Column(name="total", precision=10)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="payment", precision=10)
    public BigDecimal getPayment() {
        return this.payment;
    }
    
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    
    @Column(name="balance", precision=10)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="mode", length=150)
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }

    
    @Column(name="description", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due", length=19)
    public Date getDue() {
        return this.due;
    }
    
    public void setDue(Date due) {
        this.due = due;
    }

    
    @Column(name="subtotal")
    public Integer getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Integer subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="count1")
    public Integer getCount1() {
        return this.count1;
    }
    
    public void setCount1(Integer count1) {
        this.count1 = count1;
    }

    
    @Column(name="billnumber", length=120)
    public String getBillnumber() {
        return this.billnumber;
    }
    
    public void setBillnumber(String billnumber) {
        this.billnumber = billnumber;
    }

    
    @Column(name="status", nullable=false, length=30)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


