package com.product.entity;
// Generated Jan 28, 2018 2:52:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockSales generated by hbm2java
 */
@Entity
@Table(name="stock_sales"
    ,catalog="tml"
)
public class StockSales  implements java.io.Serializable {


     private Integer id;
     private String transactionid;
     private String stockName;
     private String category;
     private String supplierName;
     private BigDecimal sellingPrice;
     private long quantity;
     private BigDecimal amount;
     private Date date;
     private String username;
     private String customerId;
     private BigDecimal subtotal;
     private BigDecimal payment;
     private BigDecimal balance;
     private long discount;
     private long tax;
     private String taxDis;
     private long disAmount;
     private long grandTotal;
     private Date due;
     private String mode;
     private String description;
     private int count1;
     private String billnumber;

    public StockSales() {
    }

    public StockSales(String transactionid, String stockName, String category, String supplierName, BigDecimal sellingPrice, long quantity, BigDecimal amount, Date date, String username, String customerId, BigDecimal subtotal, BigDecimal payment, BigDecimal balance, long discount, long tax, String taxDis, long disAmount, long grandTotal, Date due, String mode, String description, int count1, String billnumber) {
       this.transactionid = transactionid;
       this.stockName = stockName;
       this.category = category;
       this.supplierName = supplierName;
       this.sellingPrice = sellingPrice;
       this.quantity = quantity;
       this.amount = amount;
       this.date = date;
       this.username = username;
       this.customerId = customerId;
       this.subtotal = subtotal;
       this.payment = payment;
       this.balance = balance;
       this.discount = discount;
       this.tax = tax;
       this.taxDis = taxDis;
       this.disAmount = disAmount;
       this.grandTotal = grandTotal;
       this.due = due;
       this.mode = mode;
       this.description = description;
       this.count1 = count1;
       this.billnumber = billnumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="transactionid", nullable=false, length=250)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="stock_name", nullable=false, length=200)
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    
    @Column(name="category", nullable=false, length=120)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="supplier_name", nullable=false, length=200)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="selling_price", nullable=false, precision=10)
    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    
    @Column(name="quantity", nullable=false)
    public long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="username", nullable=false, length=120)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="customer_id", nullable=false, length=120)
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="subtotal", nullable=false, precision=10)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="payment", nullable=false, precision=10)
    public BigDecimal getPayment() {
        return this.payment;
    }
    
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    
    @Column(name="balance", nullable=false, precision=10)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="discount", nullable=false, precision=10, scale=0)
    public long getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(long discount) {
        this.discount = discount;
    }

    
    @Column(name="tax", nullable=false, precision=10, scale=0)
    public long getTax() {
        return this.tax;
    }
    
    public void setTax(long tax) {
        this.tax = tax;
    }

    
    @Column(name="tax_dis", nullable=false, length=100)
    public String getTaxDis() {
        return this.taxDis;
    }
    
    public void setTaxDis(String taxDis) {
        this.taxDis = taxDis;
    }

    
    @Column(name="dis_amount", nullable=false, precision=10, scale=0)
    public long getDisAmount() {
        return this.disAmount;
    }
    
    public void setDisAmount(long disAmount) {
        this.disAmount = disAmount;
    }

    
    @Column(name="grand_total", nullable=false, precision=10, scale=0)
    public long getGrandTotal() {
        return this.grandTotal;
    }
    
    public void setGrandTotal(long grandTotal) {
        this.grandTotal = grandTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="due", nullable=false, length=10)
    public Date getDue() {
        return this.due;
    }
    
    public void setDue(Date due) {
        this.due = due;
    }

    
    @Column(name="mode", nullable=false, length=250)
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }

    
    @Column(name="description", nullable=false, length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="count1", nullable=false)
    public int getCount1() {
        return this.count1;
    }
    
    public void setCount1(int count1) {
        this.count1 = count1;
    }

    
    @Column(name="billnumber", nullable=false, length=120)
    public String getBillnumber() {
        return this.billnumber;
    }
    
    public void setBillnumber(String billnumber) {
        this.billnumber = billnumber;
    }




}


