package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier",
         catalog = "tml"
)
public class Supplier implements java.io.Serializable {

    private Integer id;
    private String supId;
    private String supName;
    private String supAddress;
    private String supContact01;
    private String supContact02;
    private String date;
    private String status;

    public Supplier() {
    }

    public Supplier(String supId, String supName, String supAddress, String supContact01, String supContact02, String date, String status) {
        this.supId = supId;
        this.supName = supName;
        this.supAddress = supAddress;
        this.supContact01 = supContact01;
        this.supContact02 = supContact02;
        this.date = date;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "sup_id", length = 30)
    public String getSupId() {
        return this.supId;
    }

    public void setSupId(String supId) {
        this.supId = supId;
    }

    @Column(name = "sup_name", length = 100)
    public String getSupName() {
        return this.supName;
    }

    public void setSupName(String supName) {
        this.supName = supName;
    }

    @Column(name = "sup_address", length = 100)
    public String getSupAddress() {
        return this.supAddress;
    }

    public void setSupAddress(String supAddress) {
        this.supAddress = supAddress;
    }

    @Column(name = "sup_contact_01", length = 30)
    public String getSupContact01() {
        return this.supContact01;
    }

    public void setSupContact01(String supContact01) {
        this.supContact01 = supContact01;
    }

    @Column(name = "sup_contact_02", length = 30)
    public String getSupContact02() {
        return this.supContact02;
    }

    public void setSupContact02(String supContact02) {
        this.supContact02 = supContact02;
    }

    @Column(name = "date", length = 50)
    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @Column(name = "status", length = 10)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
