package com.product.entity;
// Generated Jan 28, 2018 2:52:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SupplierDetails generated by hbm2java
 */
@Entity
@Table(name="supplier_details"
    ,catalog="tml"
)
public class SupplierDetails  implements java.io.Serializable {


     private Integer id;
     private String supplierName;
     private String supplierAddress;
     private String supplierContact1;
     private String supplierContact2;
     private int balance;

    public SupplierDetails() {
    }

    public SupplierDetails(String supplierName, String supplierAddress, String supplierContact1, String supplierContact2, int balance) {
       this.supplierName = supplierName;
       this.supplierAddress = supplierAddress;
       this.supplierContact1 = supplierContact1;
       this.supplierContact2 = supplierContact2;
       this.balance = balance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="supplier_name", nullable=false, length=200)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="supplier_address", nullable=false, length=500)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }
    
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    
    @Column(name="supplier_contact1", nullable=false, length=100)
    public String getSupplierContact1() {
        return this.supplierContact1;
    }
    
    public void setSupplierContact1(String supplierContact1) {
        this.supplierContact1 = supplierContact1;
    }

    
    @Column(name="supplier_contact2", nullable=false, length=100)
    public String getSupplierContact2() {
        return this.supplierContact2;
    }
    
    public void setSupplierContact2(String supplierContact2) {
        this.supplierContact2 = supplierContact2;
    }

    
    @Column(name="balance", nullable=false)
    public int getBalance() {
        return this.balance;
    }
    
    public void setBalance(int balance) {
        this.balance = balance;
    }




}


