package com.product.entity;
// Generated Jan 28, 2018 2:52:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name="transactions"
    ,catalog="tml"
)
public class Transactions  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String customer;
     private String supplier;
     private BigDecimal subtotal;
     private BigDecimal payment;
     private BigDecimal balance;
     private Date due;
     private Date date;
     private String rid;
     private String receiptid;

    public Transactions() {
    }

    public Transactions(String type, String customer, String supplier, BigDecimal subtotal, BigDecimal payment, BigDecimal balance, Date due, Date date, String rid, String receiptid) {
       this.type = type;
       this.customer = customer;
       this.supplier = supplier;
       this.subtotal = subtotal;
       this.payment = payment;
       this.balance = balance;
       this.due = due;
       this.date = date;
       this.rid = rid;
       this.receiptid = receiptid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="customer", nullable=false, length=250)
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    
    @Column(name="supplier", nullable=false, length=250)
    public String getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="subtotal", nullable=false, precision=10)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="payment", nullable=false, precision=10)
    public BigDecimal getPayment() {
        return this.payment;
    }
    
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    
    @Column(name="balance", nullable=false, precision=10)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due", nullable=false, length=19)
    public Date getDue() {
        return this.due;
    }
    
    public void setDue(Date due) {
        this.due = due;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="rid", nullable=false, length=120)
    public String getRid() {
        return this.rid;
    }
    
    public void setRid(String rid) {
        this.rid = rid;
    }

    
    @Column(name="receiptid", nullable=false, length=200)
    public String getReceiptid() {
        return this.receiptid;
    }
    
    public void setReceiptid(String receiptid) {
        this.receiptid = receiptid;
    }




}


