package com.product.entity;
// Generated Feb 6, 2018 5:16:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="tml"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String email;
     private String password;
     private String username;
     private String utype;
     private String imagePath;
     private String secretAnswer;
     private String access;

    public User() {
    }

    public User(String fname, String lname, String email, String password, String username, String utype, String imagePath, String secretAnswer, String access) {
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.password = password;
       this.username = username;
       this.utype = utype;
       this.imagePath = imagePath;
       this.secretAnswer = secretAnswer;
       this.access = access;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="fname", length=50)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="lname", length=50)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="username", length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="utype", length=30)
    public String getUtype() {
        return this.utype;
    }
    
    public void setUtype(String utype) {
        this.utype = utype;
    }

    
    @Column(name="image_path", length=200)
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    
    @Column(name="secret_answer", length=100)
    public String getSecretAnswer() {
        return this.secretAnswer;
    }
    
    public void setSecretAnswer(String secretAnswer) {
        this.secretAnswer = secretAnswer;
    }

    
    @Column(name="access", length=5)
    public String getAccess() {
        return this.access;
    }
    
    public void setAccess(String access) {
        this.access = access;
    }




}


